version: '3'

volumes: 
  dynamodb_data:

services:
  dynamodb:
    container_name: ddb
    image: amazon/dynamodb-local
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal
    volumes:
     - dynamodb_data:/home/dynamodblocal
    ports:
     - "4000:8000"